# Site settings
title: Poet Notes
email: kurrisudarshanaug12@gmail.com
description: Penned down from the worlds best authors 
baseurl: "/poet-notes"
twitter_username: kurrisudarshan
avatar: "https://pbs.twimg.com/profile_images/493785076241428480/DbFhi5jH.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "kurri sudarshan" # Set default author name
      categories: "poetry"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
